use tauri_plugin_sql::{Migration, MigrationKind};

pub const DB_URL: &str = "sqlite:pontoscan.db";

pub fn migrations() -> Vec<Migration> {
    vec![
        Migration {
            version: 1,
            description: "create core schema",
            sql: include_str!("../migrations/0001_init.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 2,
            description: "track imported files for duplicate detection",
            sql: include_str!("../migrations/0002_import_files.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 3,
            description: "track whole source files for multi-page batch imports",
            sql: include_str!("../migrations/0003_source_files.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 4,
            description: "log every import attempt with a real status",
            sql: include_str!("../migrations/0004_source_file_status.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 5,
            description: "link imports back to their whole original file",
            sql: include_str!("../migrations/0005_import_source_file.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 6,
            description: "store how many punch columns an import's grid needs",
            sql: include_str!("../migrations/0006_import_max_punches.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 7,
            description: "add clients, scoped one-to-many under companies",
            sql: include_str!("../migrations/0007_clients.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 8,
            description: "clients are many-to-many with companies, not one-to-many",
            sql: include_str!("../migrations/0008_clients_many_to_many.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 9,
            description: "store each import's period aggregates instead of recomputing them live",
            sql: include_str!("../migrations/0009_import_period_aggregates.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 10,
            description: "split absence minutes into falta (no valid pair) and atraso (short despite a pair)",
            sql: include_str!("../migrations/0010_import_late_minutes.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 11,
            description: "count days with a pending (odd) punch count per import",
            sql: include_str!("../migrations/0011_import_pending_count.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 12,
            description: "scope source files to their import type (timesheet vs. payment)",
            sql: include_str!("../migrations/0012_source_file_import_type.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 13,
            description: "define reusable payment import templates (column mapping only, not execution)",
            sql: include_str!("../migrations/0013_payment_templates.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 14,
            description: "let a payment template target a set of sheets instead of a single fixed one",
            sql: include_str!("../migrations/0014_payment_template_multi_sheet.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 15,
            description: "split a payment template into per-sheet-group header row + column mapping",
            sql: include_str!("../migrations/0015_payment_template_groups.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 16,
            description: "let each company set its own night-shift hour boundaries",
            sql: include_str!("../migrations/0016_company_night_shift_hours.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 17,
            description: "add matricula to employees, completing the cpf/matricula/nome identifier precedence",
            sql: include_str!("../migrations/0017_employee_matricula.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 18,
            description: "track imported payment shifts, one row per work shift",
            sql: include_str!("../migrations/0018_payment_shifts.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 19,
            description: "drop payment_template_groups.header_row — row validity is decided at import time by date-parseability instead",
            sql: include_str!("../migrations/0019_payment_template_drop_header_row.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 20,
            description: "drop payment_templates.client_id and decimal_separator — client is now resolved per row via rules, decimal separator was never used",
            sql: include_str!("../migrations/0020_payment_template_drop_client_and_decimal.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 21,
            description: "add payment_template_rules — an if/else-if/else chain routing each row to a company/client by a mapped field's value",
            sql: include_str!("../migrations/0021_payment_template_rules.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 22,
            description: "normalize payment_shifts.schedule into start/end minutes instead of raw text",
            sql: include_str!("../migrations/0022_payment_shift_schedule_minutes.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 23,
            description: "drop payment_templates.sample_file_path/sample_file_name — no longer persisted, only used transiently while building the mapping",
            sql: include_str!("../migrations/0023_payment_template_drop_sample_file.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 24,
            description: "add payment_templates.identifier_priority — configurable ordered list of AND'd identifier-field attempts, replacing the hardcoded cpf/matricula/nome precedence",
            sql: include_str!("../migrations/0024_payment_template_identifier_priority.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 25,
            description: "add a per-tentativa case-insensitive flag to payment_templates.identifier_priority, matching payment_template_rules' values",
            sql: include_str!("../migrations/0025_payment_template_identifier_case.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 26,
            description: "add payment_template_status_rules — an optional if/else-if/else chain deciding a shift's initial status from a mapped field's value",
            sql: include_str!("../migrations/0026_payment_template_status_rules.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 27,
            description: "add employee_aliases — possíveis nomes a colaborador can also be matched by during payment import",
            sql: include_str!("../migrations/0027_employee_aliases.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 28,
            description: "add companies.night_shift_rule — which rule decides a payment shift counts as noturno against the company's night window",
            sql: include_str!("../migrations/0028_company_night_shift_rule.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 29,
            description: "add payment_value_rules — an optional per-company if/else-if/else chain deciding a shift's Valor from its own duration",
            sql: include_str!("../migrations/0029_company_payment_value_rules.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 30,
            description: "switch payment_value_rules' threshold from decimal hours to whole minutes",
            sql: include_str!("../migrations/0030_payment_value_rules_threshold_minutes.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 31,
            description: "add payment_shifts.previous_shift_id — links a 'pago' row back to the pendente/erro row it replaces, so paying never mutates history",
            sql: include_str!("../migrations/0031_payment_shift_previous.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 32,
            description: "add employee_templates — reusable column-mapping templates for the colaboradores import flow, mirroring payment_templates but without company/client routing rules, date parsing, or status rules",
            sql: include_str!("../migrations/0032_employee_templates.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 33,
            description: "add employee_template_groups.header_row — marks the last header/title row per sheet group, so import can start right after it",
            sql: include_str!("../migrations/0033_employee_template_header_row.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 34,
            description: "backfill employees.cpf to digits-only for any row stored punctuated by the timesheet-PDF-import path, before that path was fixed to normalize like every other write path",
            sql: include_str!("../migrations/0034_normalize_employee_cpf.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 35,
            description: "add payment_shifts.extra_data — raw values of columns the template left unmapped, kept for history instead of discarded",
            sql: include_str!("../migrations/0035_payment_shift_extra_data.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 36,
            description: "track a payment import's source URL and last-known remote signature, for reimport-when-changed detection",
            sql: include_str!("../migrations/0036_source_file_url.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 37,
            description: "add source_url_settings — per-URL opt-out of the automatic remote-change check",
            sql: include_str!("../migrations/0037_source_url_settings.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 38,
            description: "add per-URL check interval override and source_url_check_log — full history of the automatic remote-change check, for the Verificação automática page",
            sql: include_str!("../migrations/0038_source_url_check_tracking.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 39,
            description: "add source_url_settings.reimport_period_start/end — the Período filters to replay automatically on a detected-change reimport",
            sql: include_str!("../migrations/0039_source_url_reimport_filters.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 40,
            description: "add source_url_settings.reimport_template_id — which template to apply on an automatic reimport",
            sql: include_str!("../migrations/0040_source_url_reimport_template.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 41,
            description: "add source_url_settings.tracking_enabled — explicit opt-in gate, replacing the old implicit 'any URL-sourced save is tracked' behavior",
            sql: include_str!("../migrations/0041_source_url_tracking_enabled.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 42,
            description: "add source_url_reimport_configs — a tracked URL can have multiple independent reimport recipes (template + fixed or relative Período), each flagging its own reimport opportunity",
            sql: include_str!("../migrations/0042_source_url_reimport_configs.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 43,
            description: "move check_disabled/check_interval_minutes from source_url_settings (per URL) to source_url_reimport_configs (per config) — each reimport config now runs on its own schedule",
            sql: include_str!("../migrations/0043_reimport_config_check_settings.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 44,
            description: "backfill NULL source_url_reimport_configs.check_interval_minutes to 5 — the per-config interval is now mandatory, the global default setting is going away",
            sql: include_str!("../migrations/0044_reimport_config_interval_required.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 45,
            description: "add payment_shifts.edited_manually and payment_settings.keep_manual_edits — reprocessing a duplicate payment shift can now skip one whose current row was a deliberate manual action instead of silently superseding it",
            sql: include_str!("../migrations/0045_payment_shifts_manual_edits.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 46,
            description: "add source_url_reimport_configs.keep_manual_edits — each reimport config now carries its own choice of whether to skip manually-edited matches, captured at creation and editable on Verificação automática",
            sql: include_str!("../migrations/0046_reimport_config_keep_manual_edits.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 47,
            description: "preserve whether each template sheet is included or disabled, so hidden sheets reappear when editing a saved template",
            sql: include_str!("../migrations/0047_template_sheet_included.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 48,
            description: "add payment_value_rules.conditions_json — narrows a pay-value rule step to shifts matching Data/Local/Função/Horário conditions before its duration check runs",
            sql: include_str!("../migrations/0048_payment_value_rules_conditions.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 49,
            description: "add payment_settings.visible_columns_json — which columns of the Pagamentos table are shown, NULL meaning all of them",
            sql: include_str!("../migrations/0049_payment_settings_visible_columns.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 50,
            description: "add accepted_file_kinds_json to payment_templates and employee_templates — a template can now accept more than one file format at import time",
            sql: include_str!("../migrations/0050_template_accepted_file_kinds.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 51,
            description: "add payment_export_templates — user-designed layouts (columns, colors, grouping, subtotal rows) for exporting payment shifts to a styled .xlsx",
            sql: include_str!("../migrations/0051_payment_export_templates.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 52,
            description: "add deleted_at to payment_shifts — 'Remover' soft-deletes a shift's whole history chain instead of physically deleting it, so a later reimport can recognize and flag it instead of silently recreating it",
            sql: include_str!("../migrations/0052_payment_shifts_soft_delete.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 53,
            description: "add source_url_check_diffs and last_deep_check_* signature columns — a background check that finds a header change now also downloads, parses and diffs against what's saved, recording exactly what changed instead of just 'changed'",
            sql: include_str!("../migrations/0053_source_url_check_diffs.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 54,
            description: "add source_url_settings.last_deep_check_result — the deep diff, not the header check, now decides what a check's Resultado column shows",
            sql: include_str!("../migrations/0054_deep_check_drives_result.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 55,
            description: "add source_url_settings.last_deep_check_log_id — a check that reuses the cached deep-check verdict now copies that run's diff rows onto its own check_log_id too, so Detalhes is never blank just because the download/parse was skipped",
            sql: include_str!("../migrations/0055_deep_check_log_id.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 56,
            description: "add payment_shifts.source_row_number/source_sheet_name (indexed) — promoted out of extra_data so the deep-check diff can look up 'what shift used to sit at this row/aba' when an identity-field edit breaks the usual identity match",
            sql: include_str!("../migrations/0056_payment_shift_source_position.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 57,
            description: "backfill payment_shifts.source_row_number/source_sheet_name from extra_data's old 'linha de origem'/'aba de origem' text for every row imported before 0056 — otherwise the deep-check position fallback finds nothing for any pre-existing shift",
            sql: include_str!("../migrations/0057_backfill_payment_shift_source_position.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 58,
            description: "add source_url_reimport_configs.auto_apply_enabled/auto_apply_overwrite_manual_edits/auto_apply_overwrite_paid and source_url_check_diffs.applied — lets a reimport config write a change the automatic verification finds straight to payment_shifts instead of only leaving it pending for manual review",
            sql: include_str!("../migrations/0058_reimport_auto_apply.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 59,
            description: "add payment_template_rules.conditions_json/payment_template_status_rules.conditions_json — a routing/status rule can test several mapped fields at once (AND), not just one",
            sql: include_str!("../migrations/0059_rule_conditions.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 60,
            description: "add payment_shifts.client_id/company_id (backfilled from the current employee) — snapshots which client/company a turno belonged to at import time instead of deriving it live through employees, so moving an employee to a different client later doesn't retroactively rewrite historical turnos",
            sql: include_str!("../migrations/0060_payment_shift_client_snapshot.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 61,
            description: "same as 0060, for imports (Cartão Ponto) instead of payment_shifts",
            sql: include_str!("../migrations/0061_import_client_snapshot.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 62,
            description: "clients gain the same optional night-shift window/rule and pay-value-chain overrides companies have (client_payment_value_rules mirrors payment_value_rules) — NULL/empty means \"inherit the company's\", client wins when set",
            sql: include_str!("../migrations/0062_client_payment_rules.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 63,
            description: "add source_url_check_log_configs — which reimport configs a check attempt actually evaluated, so due-ness and history become per-config instead of shared per URL",
            sql: include_str!("../migrations/0063_source_url_check_log_configs.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 64,
            description: "source_url_check_log_configs gains template_id/template_name/period_start/period_end — a snapshot of what a config's check attempt actually used, since the live config can be edited or deleted afterward",
            sql: include_str!("../migrations/0064_check_log_config_snapshot.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 65,
            description: "source_url_check_diffs gains dismissed_at — lets the user acknowledge (\"Visto\") a specific diff/error row without it counting toward the pending-updates banner, without suppressing a later occurrence of the same problem",
            sql: include_str!("../migrations/0065_check_diffs_dismissed.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 66,
            description: "add dismissed_diff_fingerprints — content-based \"Visto\" suppression, so a later check whose diff has identical content to one already dismissed is auto-dismissed on arrival instead of re-alerting",
            sql: include_str!("../migrations/0066_dismissed_diff_fingerprints.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 67,
            description: "employees.UNIQUE(company_id, cpf) widened to (company_id, client_id, cpf) — the old constraint predated client_id and blocked creating/moving an employee into a company that already has a different employee sharing that CPF under a different client, even though the app's own duplicate checks are already client-scoped",
            sql: include_str!("../migrations/0067_employee_unique_per_client.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 68,
            description: "add roles/role_aliases — função moves from free-text payment_shifts.role to a real cadastro (scoped per company, mirroring employees/employee_aliases), plus payment_shifts.role_id and a backfill linking every existing shift's role text to a função",
            sql: include_str!("../migrations/0068_roles.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 69,
            description: "drop payment_shifts.role — role_id (backfilled 100% in 0068) is now the only representation of a turno's função, exactly mirroring how employee_id (not a redundant employee-name text column) already works",
            sql: include_str!("../migrations/0069_payment_shift_role_fk_only.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 70,
            description: "backfill payment_shifts.edited_manually for markPaymentShiftPaid/revertPaymentShiftToPending rows written before those two transitions stopped forcing it to 1 — only a genuine editPaymentShift hop anywhere in a row's ancestry should still read edited_manually",
            sql: include_str!("../migrations/0070_backfill_edited_manually.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 71,
            description: "employees.UNIQUE(company_id, client_id, cpf) narrowed to UNIQUE(client_id, cpf) — a colaborador is one person per cliente now, not one person per (cliente, empresa); company_id/matricula move off employees onto the new employee_companies (one row per empresa a colaborador is linked to), fixing the same person showing up as a separate duplicate colaborador per empresa",
            sql: include_str!("../migrations/0071_employee_company_link.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 72,
            description: "employees.UNIQUE(client_id, cpf) narrowed to UNIQUE(cpf) — a colaborador is one person globally now, not one person per cliente; employee_companies (employee_id, company_id, matricula) replaced by employee_client_companies (employee_id, client_id, company_id, matricula), since a empresa can already serve more than one cliente, so a colaborador's empresa link has to say which cliente it's for",
            sql: include_str!("../migrations/0072_employee_client_link.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 73,
            description: "one-time cleanup: merges employees rows sharing the exact same name (case/whitespace-insensitive) but different CPFs — 0072's CPF-based merge can't catch these since the CPFs themselves differ; user-confirmed these are genuinely the same person (data-entry mistake on the CPF), not a general auto-merge rule",
            sql: include_str!("../migrations/0073_merge_duplicate_names.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 74,
            description: "adds payment_audits table for the Conferência de Pagamentos feature — records manual bank-statement verification of paid shifts, separate from payment_shifts since only the erro outcome is a real state transition",
            sql: include_str!("../migrations/0074_payment_audits.sql"),
            kind: MigrationKind::Up,
        },
    ]
}
