use tauri_plugin_sql::{Migration, MigrationKind};

pub const DB_URL: &str = "sqlite:pontoscan.db";

pub fn migrations() -> Vec<Migration> {
    vec![
        Migration {
            version: 1,
            description: "create core schema",
            sql: include_str!("../migrations/0001_init.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 2,
            description: "track imported files for duplicate detection",
            sql: include_str!("../migrations/0002_import_files.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 3,
            description: "track whole source files for multi-page batch imports",
            sql: include_str!("../migrations/0003_source_files.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 4,
            description: "log every import attempt with a real status",
            sql: include_str!("../migrations/0004_source_file_status.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 5,
            description: "link imports back to their whole original file",
            sql: include_str!("../migrations/0005_import_source_file.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 6,
            description: "store how many punch columns an import's grid needs",
            sql: include_str!("../migrations/0006_import_max_punches.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 7,
            description: "add clients, scoped one-to-many under companies",
            sql: include_str!("../migrations/0007_clients.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 8,
            description: "clients are many-to-many with companies, not one-to-many",
            sql: include_str!("../migrations/0008_clients_many_to_many.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 9,
            description: "store each import's period aggregates instead of recomputing them live",
            sql: include_str!("../migrations/0009_import_period_aggregates.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 10,
            description: "split absence minutes into falta (no valid pair) and atraso (short despite a pair)",
            sql: include_str!("../migrations/0010_import_late_minutes.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 11,
            description: "count days with a pending (odd) punch count per import",
            sql: include_str!("../migrations/0011_import_pending_count.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 12,
            description: "scope source files to their import type (timesheet vs. payment)",
            sql: include_str!("../migrations/0012_source_file_import_type.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 13,
            description: "define reusable payment import templates (column mapping only, not execution)",
            sql: include_str!("../migrations/0013_payment_templates.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 14,
            description: "let a payment template target a set of sheets instead of a single fixed one",
            sql: include_str!("../migrations/0014_payment_template_multi_sheet.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 15,
            description: "split a payment template into per-sheet-group header row + column mapping",
            sql: include_str!("../migrations/0015_payment_template_groups.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 16,
            description: "let each company set its own night-shift hour boundaries",
            sql: include_str!("../migrations/0016_company_night_shift_hours.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 17,
            description: "add matricula to employees, completing the cpf/matricula/nome identifier precedence",
            sql: include_str!("../migrations/0017_employee_matricula.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 18,
            description: "track imported payment shifts, one row per work shift",
            sql: include_str!("../migrations/0018_payment_shifts.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 19,
            description: "drop payment_template_groups.header_row — row validity is decided at import time by date-parseability instead",
            sql: include_str!("../migrations/0019_payment_template_drop_header_row.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 20,
            description: "drop payment_templates.client_id and decimal_separator — client is now resolved per row via rules, decimal separator was never used",
            sql: include_str!("../migrations/0020_payment_template_drop_client_and_decimal.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 21,
            description: "add payment_template_rules — an if/else-if/else chain routing each row to a company/client by a mapped field's value",
            sql: include_str!("../migrations/0021_payment_template_rules.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 22,
            description: "normalize payment_shifts.schedule into start/end minutes instead of raw text",
            sql: include_str!("../migrations/0022_payment_shift_schedule_minutes.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 23,
            description: "drop payment_templates.sample_file_path/sample_file_name — no longer persisted, only used transiently while building the mapping",
            sql: include_str!("../migrations/0023_payment_template_drop_sample_file.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 24,
            description: "add payment_templates.identifier_priority — configurable ordered list of AND'd identifier-field attempts, replacing the hardcoded cpf/matricula/nome precedence",
            sql: include_str!("../migrations/0024_payment_template_identifier_priority.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 25,
            description: "add a per-tentativa case-insensitive flag to payment_templates.identifier_priority, matching payment_template_rules' values",
            sql: include_str!("../migrations/0025_payment_template_identifier_case.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 26,
            description: "add payment_template_status_rules — an optional if/else-if/else chain deciding a shift's initial status from a mapped field's value",
            sql: include_str!("../migrations/0026_payment_template_status_rules.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 27,
            description: "add employee_aliases — possíveis nomes a colaborador can also be matched by during payment import",
            sql: include_str!("../migrations/0027_employee_aliases.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 28,
            description: "add companies.night_shift_rule — which rule decides a payment shift counts as noturno against the company's night window",
            sql: include_str!("../migrations/0028_company_night_shift_rule.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 29,
            description: "add payment_value_rules — an optional per-company if/else-if/else chain deciding a shift's Valor from its own duration",
            sql: include_str!("../migrations/0029_company_payment_value_rules.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 30,
            description: "switch payment_value_rules' threshold from decimal hours to whole minutes",
            sql: include_str!("../migrations/0030_payment_value_rules_threshold_minutes.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 31,
            description: "add payment_shifts.previous_shift_id — links a 'pago' row back to the pendente/erro row it replaces, so paying never mutates history",
            sql: include_str!("../migrations/0031_payment_shift_previous.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 32,
            description: "add employee_templates — reusable column-mapping templates for the colaboradores import flow, mirroring payment_templates but without company/client routing rules, date parsing, or status rules",
            sql: include_str!("../migrations/0032_employee_templates.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 33,
            description: "add employee_template_groups.header_row — marks the last header/title row per sheet group, so import can start right after it",
            sql: include_str!("../migrations/0033_employee_template_header_row.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 34,
            description: "backfill employees.cpf to digits-only for any row stored punctuated by the timesheet-PDF-import path, before that path was fixed to normalize like every other write path",
            sql: include_str!("../migrations/0034_normalize_employee_cpf.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 35,
            description: "add payment_shifts.extra_data — raw values of columns the template left unmapped, kept for history instead of discarded",
            sql: include_str!("../migrations/0035_payment_shift_extra_data.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 36,
            description: "track a payment import's source URL and last-known remote signature, for reimport-when-changed detection",
            sql: include_str!("../migrations/0036_source_file_url.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 37,
            description: "add source_url_settings — per-URL opt-out of the automatic remote-change check",
            sql: include_str!("../migrations/0037_source_url_settings.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 38,
            description: "add per-URL check interval override and source_url_check_log — full history of the automatic remote-change check, for the Verificação automática page",
            sql: include_str!("../migrations/0038_source_url_check_tracking.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 39,
            description: "add source_url_settings.reimport_period_start/end — the Período filters to replay automatically on a detected-change reimport",
            sql: include_str!("../migrations/0039_source_url_reimport_filters.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 40,
            description: "add source_url_settings.reimport_template_id — which template to apply on an automatic reimport",
            sql: include_str!("../migrations/0040_source_url_reimport_template.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 41,
            description: "add source_url_settings.tracking_enabled — explicit opt-in gate, replacing the old implicit 'any URL-sourced save is tracked' behavior",
            sql: include_str!("../migrations/0041_source_url_tracking_enabled.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 42,
            description: "add source_url_reimport_configs — a tracked URL can have multiple independent reimport recipes (template + fixed or relative Período), each flagging its own reimport opportunity",
            sql: include_str!("../migrations/0042_source_url_reimport_configs.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 43,
            description: "move check_disabled/check_interval_minutes from source_url_settings (per URL) to source_url_reimport_configs (per config) — each reimport config now runs on its own schedule",
            sql: include_str!("../migrations/0043_reimport_config_check_settings.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 44,
            description: "backfill NULL source_url_reimport_configs.check_interval_minutes to 5 — the per-config interval is now mandatory, the global default setting is going away",
            sql: include_str!("../migrations/0044_reimport_config_interval_required.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 45,
            description: "add payment_shifts.edited_manually and payment_settings.keep_manual_edits — reprocessing a duplicate payment shift can now skip one whose current row was a deliberate manual action instead of silently superseding it",
            sql: include_str!("../migrations/0045_payment_shifts_manual_edits.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 46,
            description: "add source_url_reimport_configs.keep_manual_edits — each reimport config now carries its own choice of whether to skip manually-edited matches, captured at creation and editable on Verificação automática",
            sql: include_str!("../migrations/0046_reimport_config_keep_manual_edits.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 47,
            description: "preserve whether each template sheet is included or disabled, so hidden sheets reappear when editing a saved template",
            sql: include_str!("../migrations/0047_template_sheet_included.sql"),
            kind: MigrationKind::Up,
        },
    ]
}
